# Generated by Django 5.0 on 2023-12-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='static/img/Logo.png', upload_to=''),
        ),
    ]
